# Generated by Django 3.0.5 on 2020-05-09 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.TextField(max_length=50)),
                ('adresse', models.CharField(max_length=500)),
                ('nombre_personnes', models.IntegerField()),
            ],
            options={
                'ordering': ['user'],
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('nom', models.CharField(help_text='Enter field documentation', max_length=50)),
                ('type_produit', models.CharField(choices=[('medicament', 'medicament'), ('cosmetique', 'cosmetique'), ('viande', 'viande'), ('poisson', 'poisson'), ('produit ménager', 'produit ménager'), ('légume', 'légume'), ('fruit', 'fruit'), ('boisson', 'boisson'), ('epicerie', 'epicerie')], max_length=100)),
                ('id_p', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ['id_p'],
            },
        ),
        migrations.CreateModel(
            name='Selection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choix', models.TextField(default=' ')),
            ],
            options={
                'ordering': ['choix'],
            },
        ),
    ]
