# Generated by Django 3.0.5 on 2020-05-09 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
