# Generated by Django 3.0.5 on 2020-05-11 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_client_document'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produit',
            options={'ordering': ['type_produit']},
        ),
    ]
